### ISSUE TITLE
Meeting #3 (& #4 four weeks later!)

### ISSUE THREAD

**Issue by bumblefudge** [ChainAgnostic/CASA#11]
Juan from Spruce (.eth) here, acting as volunteer Maintainer.  

Proposed time is Thurs 11ET / 5CET, quorum of codeowners already committed to making that time.  Link by request (DM me on discord at {my gh handle}#1488 or via keybase).

Nota bene @tarrencev , etc.

**Comment by bumblefudge** [comment]
@sebastinez might you be available to discuss your PRs?

**Comment by sebastinez** [comment]
Hey @bumblefudge, sorry just checked my notifications.. If there is anything I can help or respond please let me know.

**Comment by bumblefudge** [comment]
# CASA minutes 2022-01-13

- PR review
    - 88 and 71 merged - uncontroversial
        - Juan committed to fixing the Table of Contents post 71 (there are a few newer CAIPs to be added anyways)
- PGP and Radicle PRs (#53, #66)
    - Pedro: balance between hosting a registry and outsourcing to others communities'  registries
    - WYC: hosting might be simpler in cases where mature, stable registry isn't there to be deferred to
- Proposal - sever registry function from specifications that structure it
    - Ligi: Would it make sense to split specs (like CAIP 2, 10, 19...) from the namespaces? Right now almost all the other CAIPs are profiles for a given namespace
        - Juan: Some CAIPs define 2 + 10 together; others (like the 4 Hedera PRs, #75-78) define 2, 10, 19, 20 separately. Would be good to do an editorial overhaul PR that makes this cleaner
        - WYC: What if the URL looked more like `ChainAgnostic/Namespaces/{Namespace}.md` , where each namespace is a CAIP 2 top-level name like `eip155` ?
        - Pedro: We should distinguish standards process (the CAIPs like 2, 10, 19...) from namespaces 
            - Sidenote: most of the namespace work does NOT need to happen on calls!
        - OED: But not all namespaces have all the CAIPs... many only define CAIP-2, like the Radicle one
        - WYC: Proposed relationship between elements:
            -  ![image](https://user-images.githubusercontent.com/37127325/149555679-54bce19d-db85-4849-80f1-53e85c1fcbd1.png)
        - WYC: It sounds like a requirements document for what goes into each namespace doc would help! We could resource this editorial work 
        - Pedro: I'm thinking about the semantics: Namespaces = CAIP2; Domains = everything inside it (10, 19, 20...)
            - OED: But is that needed?
            - Wayne: I wonder if `domain` might be overdetermined from a Web/IETF perspective, tho; implies a highly specified heirarchy that doesn't make to what we're defining here
    - WYC: GPG and SSB should also fit in CAIP2... could the "Chain" in CASA/CAIP be updated to "Cryptosystem" to include ledgerless and P2P systems?
        - Pedro: Rename CAIP to Cryptosystem Agnostic...
        - WYC: Maybe don't rename the org, but the CAIP yeah (rough consensus not to change the C in CASA)
    - Pedro: new CAIP for to specify the registry? Is that Requirements document Wayne mentioned a CAIP or just an issue?
        - OED: what about new reqs like JSON-RPC or resolution mechanics? 
        - Pedro: Actually CAIP-2 already defines a namespace by a resolution mechanism [see #Semantics](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md#semantics), so the CAIP-2 section of any `{namespace}.md` should at least link to, if not explain, the RPC/indexer syntax/system
- Governance Topics
    - how to approve non-blockchains? how distinguish between GPG and GPG2 (random small protocols trying to become as established as, say, GPG or SSB)
        - This probably will be a question that needs to be resolved on future calls! (Rough consensus to consider in more detail later)
        - Juan will open tracking issue but await interest to mark it "next meeting" :D
    - Juan: other registries I've been involved with have had problems with change control over time; cf. the section in the [RFC that defines IANA registries](https://datatracker.ietf.org/doc/html/rfc8126#section-2.3) for one possible solution
        - Juan will open a tracking issue after the editorial PR for us to consider at a future meeting
- CACAO
    - Intro from Sergey: Use case, origins in EF/EVM harmonization and type system for future namespace profiles to be defined
    - Feedback from Wayne: This is great; perfect for Key delegations
    - WYC: What about profiles per domain/namespace? namespace included somewhere in the data model
        - OED: that's why we use did:pkh for the `iss` (issuer) field- the namespace is the prefix between did:pkh and the CAIP-2/CAIP-10 info
        - WYC: does every blockchain developer need to know what a DID is, though? it makes w3c-ccg an upstream dependency/reliance of this spec
        - OED: But did-pkh depends on CAIPs, so it's a circuar dependency more than an upstream one, non?
        - Sergey: but did:pkh isn't specified as only way of resolving, this leaves the door open to a future CAIP or URN scheme; the proposed CAIP just says it should be resolvable from the issuer field
    - Pedro: wouldn't this be moot after we register `urn:caip` at IANA?
        - rough consensus it would
        - status-quo fine for now, but might be simpler not to take external dep on a w3c-ccg or specify the 
- Next Steps
    - register `:caip:` at IANA
        - the only person on the call with IANA registration experience seems to be ligi
            - who volunteers to lead this effort
        - defer CAIP for the indexing/mapping of `{namespace}.md` files until after registration 
    - EditorialPR for the `namespaces` repo 
        - juan will undertake next week to allow time for review well before next meeting
        - juan will tag every CAIP proposer/editor whose work would get moved into the namespaces to encourage them to review and come to next meeting if necessary
    - CACAO PR (#76) to enter Last Call stage/tag before merge
