### ISSUE TITLE
Meeting #2

### ISSUE THREAD

**Issue by ligi** [ChainAgnostic/CASA#5]
Date: 7.9.2021
Topics: URI-fication of CAIPs https://twitter.com/mr_ligi/status/1425013109601755175

**Comment by ukstv** [comment]
+1 entry to the topic list: hex-strings for 721/1155 token id: https://github.com/ChainAgnostic/CAIPs/issues/58

**Comment by antoineherzog** [comment]
+1  URI-fication of CAIPs
+1 Uri-request: Being able to request a crypto payment with a URI (cf. for Ethereum https://eips.ethereum.org/EIPS/eip-681 :we could generalize this approach to all chains)

**Comment by oed** [comment]
Would like to discuss `did:pkh` and how it relates to caip-10.

Context:
* [old outdated spec](https://github.com/spruceid/ssi/blob/main/did-pkh/did-pkh-method-draft.md)
* [implementation using caip10](https://github.com/ceramicnetwork/js-ceramic/pull/1624)

**Comment by bumblefudge** [comment]
date still tbd or am i watching in the wrong places?

**Comment by ligi** [comment]
We talked abut it just today on discord - tentative date: 9.7

**Comment by antoineherzog** [comment]
Call this Tuesday September 7th, 3PM UTC+2
Good for everyone ?

**Comment by bumblefudge** [comment]
how is connect

**Comment by tarrencev** [comment]
@ligi @oed any chance i can get an invite to the discord :) tarrence#4186
