### ISSUE TITLE
Make README for the top level org that points to all of the main spaces

### ISSUE THREAD

**Issue by bmann** [ChainAgnostic/CASA#61]
For the UCAN WG https://github.com/ucan-wg and for the Fission repo https://github.com/fission-codes, we've [customized the org profile with a README](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile).

I suggest we do set this up so that we can point to a roadmap of repos and channels -- e.g. [Discussions](https://github.com/ChainAgnostic/CASA/discussions), the Discord, any calendars, etc.

**Comment by bmann** [comment]
And to be clear, this is a minor GH feature, I think we can take the README from this repo and copy it up one level. I haven't looked further into permissions required.

**Comment by bumblefudge** [comment]
[It lives](https://github.com/ChainAgnostic)!

If you think we should leave this issue open, I'd rename it to "better roadmap and overview required" and we can discuss at a future board and/or editorial meeting accordingly!  For now, I just created a duplicate table of contents to the `/CASA/readme.md` so avoid drift between the two versions, but we could just nix the latter if we're not going to put in, say, complex roadmaps or other content in there.
